spring:
  application:
    name: PRODUCT-ORDER

  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka